/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/console': RouteRecordInfo<'/console', '/console', Record<never, never>, Record<never, never>, '/console/dashboard' | '/console/logs' | '/console/models' | '/console/settings' | '/console/tokens' | '/console/topup'>,
    '/console/dashboard': RouteRecordInfo<'/console/dashboard', '/console/dashboard', Record<never, never>, Record<never, never>>,
    '/console/logs': RouteRecordInfo<'/console/logs', '/console/logs', Record<never, never>, Record<never, never>>,
    '/console/models': RouteRecordInfo<'/console/models', '/console/models', Record<never, never>, Record<never, never>>,
    '/console/settings': RouteRecordInfo<'/console/settings', '/console/settings', Record<never, never>, Record<never, never>>,
    '/console/tokens': RouteRecordInfo<'/console/tokens', '/console/tokens', Record<never, never>, Record<never, never>>,
    '/console/topup': RouteRecordInfo<'/console/topup', '/console/topup', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/models': RouteRecordInfo<'/models', '/models', Record<never, never>, Record<never, never>>,
    '/oauth/oidc': RouteRecordInfo<'/oauth/oidc', '/oauth/oidc', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/reset': RouteRecordInfo<'/reset', '/reset', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/console.vue': {
      routes: '/console' | '/console/dashboard' | '/console/logs' | '/console/models' | '/console/settings' | '/console/tokens' | '/console/topup'
      views: 'default'
    }
    'src/pages/console/dashboard.vue': {
      routes: '/console/dashboard'
      views: never
    }
    'src/pages/console/logs.vue': {
      routes: '/console/logs'
      views: never
    }
    'src/pages/console/models.vue': {
      routes: '/console/models'
      views: never
    }
    'src/pages/console/settings.vue': {
      routes: '/console/settings'
      views: never
    }
    'src/pages/console/tokens.vue': {
      routes: '/console/tokens'
      views: never
    }
    'src/pages/console/topup.vue': {
      routes: '/console/topup'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/models.vue': {
      routes: '/models'
      views: never
    }
    'src/pages/oauth/oidc.vue': {
      routes: '/oauth/oidc'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
    'src/pages/reset.vue': {
      routes: '/reset'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
